version: '3.1'

services:
  db:
    image: postgres
    container_name: ts-api-postgres
    ports:
      - 54329:5432
    volumes:
      - ./provision/database/:/docker-entrypoint-initdb.d
    env_file:
     - .env